FROM golang:1.21-alpine as build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . /app

RUN go build -o "./bin/server" ./cmd/server

FROM alpine:3.19
WORKDIR /
COPY --from=build /app/bin/server /server
COPY --from=build /app/.env /.env
ENTRYPOINT ["/server"]